<?php

use App\Livewire\Admin\Blog\AddBlog;
use App\Livewire\Admin\Blog\BlogList;
use App\Livewire\Admin\Blog\CategoryList;
use App\Livewire\Admin\Blog\UpdateBlog;
use App\Livewire\Admin\Contact\PackageEnquires;
use App\Livewire\Admin\Dashboard\Dashboard;
use App\Livewire\Admin\Faq\Faq;
use App\Livewire\Admin\Page\PageManagement;
use App\Livewire\Admin\Portfolio\PortfolioList;
use App\Livewire\Admin\RolePermission\PermissionList;
use App\Livewire\Admin\RolePermission\RoleList;
use App\Livewire\Admin\RolePermission\UserList;
use App\Livewire\Admin\Service\ServiceCategoryList;
use App\Livewire\Admin\Testimonial\TestimonialList;
use App\Livewire\Auth\Login;
use App\Livewire\FooterPage\Disclaimer;
use App\Livewire\FooterPage\RefundCancellation;
use App\Livewire\FooterPage\TermAndCondition;
use App\Livewire\PrivacyPolicy;
use App\Livewire\Public\About\About;
use App\Livewire\Public\Blog\Blog;
use App\Livewire\Public\Blog\BlogView;
use App\Livewire\Public\Branding\Index as BrandingIndex;
use App\Livewire\Public\DigitalMarkting\Index as DigitalMarktingIndex;
use App\Livewire\Public\GraphicDesigning\Index as GraphicDesigningIndex;
use App\Livewire\Public\Home\Home;
use App\Livewire\Public\Home\Home2;
use App\Livewire\Public\Home\Index;
use App\Livewire\Public\Package\SeoPackage;
use App\Livewire\Public\Package\SmoPackage;
use App\Livewire\Public\Package\StartupPackage;
use App\Livewire\Public\Portfolio\Portfolio;
use App\Livewire\Public\Service\Service;
use App\Livewire\Public\Service\ServiceView;
use App\Livewire\Public\WebDesigning\Index as WebDesigningIndex;
use App\Livewire\Public\WebDevelopment\Index as WebDevelopmentIndex;
use App\Livewire\Public\WebDevelopment\LaravelDevelopment;
use App\Livewire\Public\WebDevelopment\MernDevelopment;
use App\Livewire\Public\WebDevelopment\WordpressDevelopment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::get('/',action: Home::class)->name('home');
Route::get('/web-development',WebDevelopmentIndex::class)->name('webdevelopment');
Route::get('/seo-package',SeoPackage::class)->name('seo-package');
Route::get('/smo-package',SmoPackage::class)->name('smo-package');
Route::get('/startup-package',StartupPackage::class)->name('startup-package');
Route::get('/digital-marketing',DigitalMarktingIndex::class)->name('digital-marketing');
Route::get('/web-designing',WebDesigningIndex::class)->name('webdesigning');
Route::get('/graphic-designing',GraphicDesigningIndex::class)->name('graphicdesigning');
Route::get('/mobile-app-development',App\Livewire\Public\MobileDevelopment\Index::class)->name('mobileappdevelopment');
Route::get('/blog',Blog::class)->name('blog');
Route::get('/blog-view/{slug}',BlogView::class)->name('blog.view');
Route::get('/about',About::class)->name('about');
Route::get('/portfolio',Portfolio::class)->name('portfolio');
Route::get('/contact',App\Livewire\Public\Contact\Contact::class)->name('contact');
Route::get('/privacy-policy',PrivacyPolicy::class)->name('privacy-policy');
Route::get('/refund-policy',RefundCancellation::class)->name('refund-policy');
Route::get('/terms-and-conditions',TermAndCondition::class)->name('terms-conditions');
Route::get('/disclaimer',Disclaimer::class)->name('disclaimer');
Route::get('/branding',BrandingIndex::class)->name('branding');
Route::get('laravel-development',LaravelDevelopment::class)->name('laravel-development');
Route::get('mern-development',MernDevelopment::class)->name('mern-development');
Route::get('wordpress-development',WordpressDevelopment::class)->name('wordpress-development');
Route::get('/login',Login::class)->name('login');
Route::prefix('admin')->middleware('auth')->name('admin.')->group(function () {
    Route::get('/',Dashboard::class)->name('dashboard');
    Route::get('/page-management',PageManagement::class)->name('page-management');
    Route::get('/service-category',ServiceCategoryList::class)->name('service-category');
    Route::get('/package-enquiry',PackageEnquires::class)->name('package-enquiry');
    Route::get('/faq-management',Faq::class)->name('faq-management');
    Route::get('/Users',UserList::class)->name('users');
    Route::get('/permission',PermissionList::class)->name('permission');
    Route::get('/role-permission',RoleList::class)->name('role-permission');
    Route::get('/add-blog',AddBlog::class)->name('add-blog');
    Route::get('/contact',App\Livewire\Admin\Contact\Contact::class)->name('contact-list');
    Route::get('/portfolio',PortfolioList::class)->name('portfolio.list');
    Route::get('/update-blog/{post}',UpdateBlog::class)->name('update-blog');
    Route::get('/blog-list',BlogList::class)->name('blog-list');
    Route::get('/testimonial',TestimonialList::class)->name('testimonial');
    Route::get('/blog-category',CategoryList::class)->name('blog-category');
});


Route::get('/clear-cache', function () {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    return "Cache Cleared!";
});

Route::get("/logout", function () {
    auth()->logout();
    return redirect()->route('index');
})->name('logout');